[package]
name = "kachiclash"
version = "0.2.0"
authors = ["Daniel Dickison <kachiclash@danieldickison.com>"]
edition = "2018"
publish = false

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
actix-identity = "0.2"
actix-session = "0.3"
actix-files = "0.2"
url = "2.1"
reqwest = "0.9.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.3"
failure = "0.1.3"
envconfig = "0.6"
envconfig_derive = "0.6"
log = "0.4"
env_logger = "0.7"
chrono = "0.4"
itertools = "0.8"
oauth2 = "3.0.0-alpha.7"
result = "1.0.0"
regex = "1.3.1"
lazy_static = "1.4.0"
rand = "0.7.2"

[dependencies.rusqlite]
version = "0.21"
features = ["bundled", "chrono"]

[dependencies.askama]
version = "0.9"
features = ["with-actix-web"]
