[package]
name = "kachiclash"
version = "0.3.0"
authors = ["Daniel Dickison <kachiclash@danieldickison.com>"]
edition = "2021"
publish = false

[dependencies]
#tokio = "0.2"
actix-web = "3.3"
actix-rt = "1.1"
actix-identity = "0.3"
actix-session = "0.4"
actix-files = "0.5"
async-trait = "0.1"
url = "2.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.3"
envconfig = "0.10"
log = "0.4"
env_logger = "0.8"
chrono = "0.4"
itertools = "0.10"
result = "1.0"
regex = "1.4"
lazy_static = "1.4"
rand = "0.8"
oauth2 = "=4.0.0-alpha.2" # 4.0.0 release bumps reqwest to 0.11 which bumps tokio to 1.0, which is incompat with actix-rt
anyhow = "1.0"
askama = "0.10"
askama_actix = "0.11"
num_cpus = "1.13"

[dependencies.rusqlite]
version = "0.25"
features = ["bundled", "chrono"]

[dependencies.reqwest]
version = "0.10"
features = ["gzip", "json"]
