[package]
name = "kachiclash"
version = "0.2.0"
authors = ["Daniel Dickison <kachiclash@danieldickison.com>"]
edition = "2018"
publish = false

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
actix-identity = "0.2"
actix-session = "0.3"
actix-files = "0.2"
async-trait = "0.1.24"
url = "2.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.3"
failure = "0.1.3"
envconfig = "0.6"
envconfig_derive = "0.6"
log = "0.4"
env_logger = "0.7"
chrono = "0.4"
itertools = "0.8"
result = "1.0"
regex = "1.3"
lazy_static = "1.4"
rand = "0.7"

[dependencies.rusqlite]
version = "0.21"
features = ["bundled", "chrono"]

[dependencies.askama]
version = "0.9"
features = ["with-actix-web"]

[dependencies.reqwest]
version = "0.10.1"
features = ["gzip", "json"]

[dependencies.oauth2]
version = "3.0.0-alpha.8"
# TODO: oauth2 3.0.0-alpha.8 depends on an alpha version of reqwest 0.10, but we want the stable 0.10 for our own code. These are currently incompatible, so oauth2 requests will be made with blocking reqwest 0.9 calls for now. Revisit when oauth2 is compatible with reqwest 0.10.1
#default-features = false
#features = ["reqwest-010"]
